name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - uses: sibiraj-s/action-eslint@v2
        with:
          eslint-args: '--ignore-path=.eslintignore'
          extensions: 'js,jsx,ts,tsx'
          annotations: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: npm ci and tests
        run: |
          npm ci
          npm test
